-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity disc_cluster is
port (
    ap_ready : OUT STD_LOGIC;
    ac_e_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ac_t_V : IN STD_LOGIC_VECTOR (2 downto 0);
    cluster_threshold_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of disc_cluster is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal bvh_d_index_fu_40_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_34_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_44_p4 : STD_LOGIC_VECTOR (7 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        ap_const_lv8_0 when (tmp_fu_34_p2(0) = '1') else 
        p_Result_s_fu_44_p4;
    bvh_d_index_fu_40_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ac_t_V),32));
    
    p_Result_s_fu_44_p4_proc : process(bvh_d_index_fu_40_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_s_fu_44_p4 <= ap_const_lv8_0;
        if to_integer(unsigned(bvh_d_index_fu_40_p1)) >= ap_const_lv8_0'low and to_integer(unsigned(bvh_d_index_fu_40_p1)) <= ap_const_lv8_0'high then
            result(0) := '0';
            for i in ap_const_lv32_1'range loop
                result(0) := result(0) or ap_const_lv32_1(i);
            end loop;
            p_Result_s_fu_44_p4(to_integer(unsigned(bvh_d_index_fu_40_p1))) <= result(0);
        end if;
    end process;

    tmp_fu_34_p2 <= "1" when (unsigned(ac_e_V) < unsigned(cluster_threshold_V)) else "0";
end behav;
