-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Find_cluster is
port (
    ap_ready : OUT STD_LOGIC;
    prehits_0_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_1_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_2_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_3_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_4_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_5_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_6_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    prehits_0_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_1_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_2_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_3_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_4_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_5_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    prehits_6_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_0_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_1_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_2_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_3_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_4_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_5_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_6_e_V_read : IN STD_LOGIC_VECTOR (12 downto 0);
    curhits_0_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_1_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_2_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_3_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_4_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_5_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    curhits_6_t_V_read : IN STD_LOGIC_VECTOR (2 downto 0);
    hit_dt_V : IN STD_LOGIC_VECTOR (2 downto 0);
    seed_threshold_V : IN STD_LOGIC_VECTOR (12 downto 0);
    agg_result_x_V_write : IN STD_LOGIC_VECTOR (4 downto 0);
    agg_result_y_V_write : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Find_cluster is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv7_5 : STD_LOGIC_VECTOR (6 downto 0) := "0000101";
    constant ap_const_lv7_6 : STD_LOGIC_VECTOR (6 downto 0) := "0000110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ult_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ult1_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_demorgan_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp117_demorgan_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev1_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp117_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0115_1_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_fu_412_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal t_V_fu_362_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp8_cast_fu_420_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal t_V_2_fu_424_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_52_fu_442_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_456_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_fu_462_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_fu_468_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_11_fu_432_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_48_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0115_1_cast_cast_fu_408_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_482_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp4_fu_510_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Val2_1_fu_518_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_64_fu_536_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_546_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_fu_552_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_fu_558_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_cast_fu_526_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_s_fu_502_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_582_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_149_fu_572_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp8_fu_610_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_1_fu_602_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal e_array_V_load_fu_394_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_fu_618_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_150_fu_632_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_52_1_fu_656_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_1_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_1_fu_670_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_1_fu_676_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_s_fu_682_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0115_5_fu_642_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_1_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_1_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_151_fu_696_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp10_fu_726_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_1_fu_748_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_1_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_1_fu_758_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_1_fu_764_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_1_fu_770_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_1_fu_734_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_1_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_1_fu_718_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_1_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_794_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_152_fu_784_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp14_fu_822_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_2_fu_814_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_1_fu_830_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_1_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_153_fu_844_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_52_2_fu_868_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_2_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_2_fu_882_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_2_fu_888_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_2_fu_894_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0115_5_1_fu_854_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_2_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_2_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_154_fu_908_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp17_fu_938_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_2_fu_960_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_2_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_2_fu_970_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_2_fu_976_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_2_fu_982_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_2_fu_946_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_2_fu_954_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_2_fu_930_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_2_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_1014_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp20_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_1006_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_155_fu_996_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp21_fu_1034_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_3_fu_1026_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_2_fu_1042_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_2_fu_1050_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_156_fu_1056_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_52_3_fu_1080_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_3_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_3_fu_1094_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_3_fu_1100_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_3_fu_1106_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0115_5_2_fu_1066_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_3_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_3_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_1136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_157_fu_1120_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp24_fu_1150_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_3_fu_1172_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_3_fu_1176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_3_fu_1182_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_3_fu_1188_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_3_fu_1194_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_3_fu_1158_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_3_fu_1166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_3_fu_1142_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_3_fu_1202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp27_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_1218_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_158_fu_1208_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp28_fu_1246_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_4_fu_1238_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_3_fu_1254_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_3_fu_1262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_159_fu_1268_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_52_4_fu_1292_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_4_fu_1300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_4_fu_1306_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_4_fu_1312_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_4_fu_1318_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0115_5_3_fu_1278_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_4_fu_1286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_4_fu_1326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_1342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp30_fu_1348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_160_fu_1332_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp31_fu_1362_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_4_fu_1384_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_4_fu_1388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_4_fu_1394_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_4_fu_1400_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_4_fu_1406_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_4_fu_1370_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_4_fu_1378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_4_fu_1354_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_4_fu_1414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_1438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp34_fu_1444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1430_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_161_fu_1420_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp35_fu_1458_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_5_fu_1450_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_4_fu_1466_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_4_fu_1474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_162_fu_1480_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_52_5_fu_1504_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_53_5_fu_1512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_5_fu_1518_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_5_fu_1524_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_5_fu_1530_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0115_5_4_fu_1490_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_5_fu_1498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_5_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp36_fu_1554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp37_fu_1560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_163_fu_1544_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp38_fu_1574_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_64_5_fu_1596_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_65_5_fu_1600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_5_fu_1606_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_67_5_fu_1612_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal diff_V_1_5_fu_1618_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_1_5_fu_1582_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_63_5_fu_1590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_array_V_load_1_5_fu_1566_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_5_fu_1626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_1650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_fu_1656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp39_fu_1642_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_164_fu_1632_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sel_tmp42_fu_1670_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal e_array_V_load_6_fu_1662_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_2_5_fu_1678_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_69_5_fu_1686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_165_fu_1692_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_0115_5_5_fu_1702_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_167_fu_1714_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_8_fu_1728_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_1_fu_1744_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_2_fu_1760_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_3_fu_1776_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_4_fu_1792_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_5_fu_1808_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_2_cast_fu_1756_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_57_cast_fu_1724_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp119_fu_1824_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_57_1_cast_fu_1740_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp119_cast_fu_1830_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp118_fu_1834_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_57_4_cast_fu_1788_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_57_3_cast_fu_1772_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp121_fu_1844_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_57_6_cast_fu_1820_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_57_5_cast_fu_1804_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp122_fu_1854_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp121_cast_fu_1850_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp122_cast_fu_1860_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp120_fu_1864_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp118_cast_fu_1840_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp120_cast_fu_1870_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_8_6_fu_1880_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_2_cast_fu_1768_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_cast_fu_1736_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_1_cast_fu_1752_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp124_fu_1892_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp123_fu_1898_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_4_cast_fu_1800_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_3_cast_fu_1784_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp126_fu_1908_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_6_cast_fu_1888_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_60_5_cast_fu_1816_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp127_fu_1918_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp126_cast_fu_1914_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp127_cast_fu_1924_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp123_cast_fu_1904_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp125_fu_1928_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_166_fu_1710_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_6_fu_1874_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cc_t_V_fu_1718_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_61_6_fu_1934_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal agg_result_e_V_write_fu_1940_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_t_V_write_fu_1948_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal agg_result_nhits_V_w_fu_1956_p3 : STD_LOGIC_VECTOR (2 downto 0);


begin



    agg_result_e_V_write_fu_1940_p3 <= 
        tmp_58_6_fu_1874_p2 when (tmp_166_fu_1710_p1(0) = '1') else 
        ap_const_lv16_0;
    agg_result_nhits_V_w_fu_1956_p3 <= 
        tmp_61_6_fu_1934_p2 when (tmp_166_fu_1710_p1(0) = '1') else 
        ap_const_lv3_0;
    agg_result_t_V_write_fu_1948_p3 <= 
        cc_t_V_fu_1718_p2 when (tmp_166_fu_1710_p1(0) = '1') else 
        ap_const_lv3_0;
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= agg_result_x_V_write;
    ap_return_1 <= agg_result_y_V_write;
    ap_return_2 <= agg_result_e_V_write_fu_1940_p3;
    ap_return_3 <= agg_result_t_V_write_fu_1948_p3;
    ap_return_4 <= agg_result_nhits_V_w_fu_1956_p3;
    cc_t_V_fu_1718_p2 <= (tmp_167_fu_1714_p1 xor ap_const_lv3_4);
    diff_V_1_1_fu_770_p3 <= 
        tmp_66_1_fu_758_p2 when (tmp_65_1_fu_752_p2(0) = '1') else 
        tmp_67_1_fu_764_p2;
    diff_V_1_2_fu_982_p3 <= 
        tmp_66_2_fu_970_p2 when (tmp_65_2_fu_964_p2(0) = '1') else 
        tmp_67_2_fu_976_p2;
    diff_V_1_3_fu_1194_p3 <= 
        tmp_66_3_fu_1182_p2 when (tmp_65_3_fu_1176_p2(0) = '1') else 
        tmp_67_3_fu_1188_p2;
    diff_V_1_4_fu_1406_p3 <= 
        tmp_66_4_fu_1394_p2 when (tmp_65_4_fu_1388_p2(0) = '1') else 
        tmp_67_4_fu_1400_p2;
    diff_V_1_5_fu_1618_p3 <= 
        tmp_66_5_fu_1606_p2 when (tmp_65_5_fu_1600_p2(0) = '1') else 
        tmp_67_5_fu_1612_p2;
    diff_V_1_fu_558_p3 <= 
        tmp_66_fu_546_p2 when (tmp_65_fu_540_p2(0) = '1') else 
        tmp_67_fu_552_p2;
    diff_V_2_fu_894_p3 <= 
        tmp_54_2_fu_882_p2 when (tmp_53_2_fu_876_p2(0) = '1') else 
        tmp_55_2_fu_888_p2;
    diff_V_3_fu_1106_p3 <= 
        tmp_54_3_fu_1094_p2 when (tmp_53_3_fu_1088_p2(0) = '1') else 
        tmp_55_3_fu_1100_p2;
    diff_V_4_fu_1318_p3 <= 
        tmp_54_4_fu_1306_p2 when (tmp_53_4_fu_1300_p2(0) = '1') else 
        tmp_55_4_fu_1312_p2;
    diff_V_5_fu_1530_p3 <= 
        tmp_54_5_fu_1518_p2 when (tmp_53_5_fu_1512_p2(0) = '1') else 
        tmp_55_5_fu_1524_p2;
    diff_V_fu_468_p3 <= 
        tmp_54_fu_456_p2 when (tmp_53_fu_450_p2(0) = '1') else 
        tmp_55_fu_462_p2;
    diff_V_s_fu_682_p3 <= 
        tmp_54_1_fu_670_p2 when (tmp_53_1_fu_664_p2(0) = '1') else 
        tmp_55_1_fu_676_p2;
    e_array_V_load_1_1_fu_718_p3 <= 
        ap_const_lv13_0 when (sel_tmp1_fu_712_p2(0) = '1') else 
        curhits_2_e_V_read;
    e_array_V_load_1_2_fu_930_p3 <= 
        ap_const_lv13_0 when (sel_tmp16_fu_924_p2(0) = '1') else 
        curhits_3_e_V_read;
    e_array_V_load_1_3_fu_1142_p3 <= 
        ap_const_lv13_0 when (sel_tmp23_fu_1136_p2(0) = '1') else 
        curhits_4_e_V_read;
    e_array_V_load_1_4_fu_1354_p3 <= 
        ap_const_lv13_0 when (sel_tmp30_fu_1348_p2(0) = '1') else 
        curhits_5_e_V_read;
    e_array_V_load_1_5_fu_1566_p3 <= 
        ap_const_lv13_0 when (sel_tmp37_fu_1560_p2(0) = '1') else 
        curhits_6_e_V_read;
    e_array_V_load_1_fu_602_p3 <= 
        e_array_V_load_1_s_fu_502_p3 when (sel_tmp7_fu_596_p2(0) = '1') else 
        sel_tmp5_fu_582_p3;
    e_array_V_load_1_s_fu_502_p3 <= 
        ap_const_lv13_0 when (sel_tmp3_fu_496_p2(0) = '1') else 
        curhits_1_e_V_read;
    e_array_V_load_2_fu_814_p3 <= 
        e_array_V_load_1_1_fu_718_p3 when (sel_tmp13_fu_808_p2(0) = '1') else 
        sel_tmp11_fu_794_p3;
    e_array_V_load_3_fu_1026_p3 <= 
        e_array_V_load_1_2_fu_930_p3 when (sel_tmp20_fu_1020_p2(0) = '1') else 
        sel_tmp18_fu_1006_p3;
    e_array_V_load_4_fu_1238_p3 <= 
        e_array_V_load_1_3_fu_1142_p3 when (sel_tmp27_fu_1232_p2(0) = '1') else 
        sel_tmp25_fu_1218_p3;
    e_array_V_load_5_fu_1450_p3 <= 
        e_array_V_load_1_4_fu_1354_p3 when (sel_tmp34_fu_1444_p2(0) = '1') else 
        sel_tmp32_fu_1430_p3;
    e_array_V_load_6_fu_1662_p3 <= 
        e_array_V_load_1_5_fu_1566_p3 when (sel_tmp41_fu_1656_p2(0) = '1') else 
        sel_tmp39_fu_1642_p3;
    e_array_V_load_fu_394_p3 <= 
        curhits_0_e_V_read when (sel_tmp2_fu_388_p2(0) = '1') else 
        prehits_0_e_V_read;
    or_cond_fu_336_p2 <= (tmp_fu_328_p3 and rev_fu_322_p2);
    p_0115_1_cast_cast_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0115_1_fu_402_p2),2));
    p_0115_1_fu_402_p2 <= (sel_tmp2_fu_388_p2 or or_cond_fu_336_p2);
    p_0115_5_1_fu_854_p3 <= 
        p_Val2_2_1_fu_830_p3 when (tmp_69_1_fu_838_p2(0) = '1') else 
        tmp_153_fu_844_p4;
    p_0115_5_2_fu_1066_p3 <= 
        p_Val2_2_2_fu_1042_p3 when (tmp_69_2_fu_1050_p2(0) = '1') else 
        tmp_156_fu_1056_p4;
    p_0115_5_3_fu_1278_p3 <= 
        p_Val2_2_3_fu_1254_p3 when (tmp_69_3_fu_1262_p2(0) = '1') else 
        tmp_159_fu_1268_p4;
    p_0115_5_4_fu_1490_p3 <= 
        p_Val2_2_4_fu_1466_p3 when (tmp_69_4_fu_1474_p2(0) = '1') else 
        tmp_162_fu_1480_p4;
    p_0115_5_5_fu_1702_p3 <= 
        p_Val2_2_5_fu_1678_p3 when (tmp_69_5_fu_1686_p2(0) = '1') else 
        tmp_165_fu_1692_p4;
    p_0115_5_fu_642_p3 <= 
        p_Val2_2_fu_618_p3 when (tmp_69_fu_626_p2(0) = '1') else 
        tmp_150_fu_632_p4;
    p_Result_8_1_fu_1744_p3 <= p_0115_5_5_fu_1702_p3(1 downto 1);
    p_Result_8_2_fu_1760_p3 <= p_0115_5_5_fu_1702_p3(2 downto 2);
    p_Result_8_3_fu_1776_p3 <= p_0115_5_5_fu_1702_p3(3 downto 3);
    p_Result_8_4_fu_1792_p3 <= p_0115_5_5_fu_1702_p3(4 downto 4);
    p_Result_8_5_fu_1808_p3 <= p_0115_5_5_fu_1702_p3(5 downto 5);
    p_Result_8_6_fu_1880_p3 <= p_0115_5_5_fu_1702_p3(6 downto 6);
    p_Result_8_fu_1728_p3 <= p_0115_5_5_fu_1702_p3(0 downto 0);
    p_Val2_1_1_fu_734_p3 <= 
        p_0115_5_fu_642_p3 when (sel_tmp1_fu_712_p2(0) = '1') else 
        sel_tmp10_fu_726_p3;
    p_Val2_1_2_fu_946_p3 <= 
        p_0115_5_1_fu_854_p3 when (sel_tmp16_fu_924_p2(0) = '1') else 
        sel_tmp17_fu_938_p3;
    p_Val2_1_3_fu_1158_p3 <= 
        p_0115_5_2_fu_1066_p3 when (sel_tmp23_fu_1136_p2(0) = '1') else 
        sel_tmp24_fu_1150_p3;
    p_Val2_1_4_fu_1370_p3 <= 
        p_0115_5_3_fu_1278_p3 when (sel_tmp30_fu_1348_p2(0) = '1') else 
        sel_tmp31_fu_1362_p3;
    p_Val2_1_5_fu_1582_p3 <= 
        p_0115_5_4_fu_1490_p3 when (sel_tmp37_fu_1560_p2(0) = '1') else 
        sel_tmp38_fu_1574_p3;
    p_Val2_1_cast_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_1_fu_518_p3),7));
    p_Val2_1_fu_518_p3 <= 
        p_0115_1_cast_cast_fu_408_p1 when (sel_tmp3_fu_496_p2(0) = '1') else 
        sel_tmp4_fu_510_p3;
    p_Val2_2_1_fu_830_p3 <= 
        p_Val2_1_1_fu_734_p3 when (sel_tmp13_fu_808_p2(0) = '1') else 
        sel_tmp14_fu_822_p3;
    p_Val2_2_2_fu_1042_p3 <= 
        p_Val2_1_2_fu_946_p3 when (sel_tmp20_fu_1020_p2(0) = '1') else 
        sel_tmp21_fu_1034_p3;
    p_Val2_2_3_fu_1254_p3 <= 
        p_Val2_1_3_fu_1158_p3 when (sel_tmp27_fu_1232_p2(0) = '1') else 
        sel_tmp28_fu_1246_p3;
    p_Val2_2_4_fu_1466_p3 <= 
        p_Val2_1_4_fu_1370_p3 when (sel_tmp34_fu_1444_p2(0) = '1') else 
        sel_tmp35_fu_1458_p3;
    p_Val2_2_5_fu_1678_p3 <= 
        p_Val2_1_5_fu_1582_p3 when (sel_tmp41_fu_1656_p2(0) = '1') else 
        sel_tmp42_fu_1670_p3;
    p_Val2_2_fu_618_p3 <= 
        p_Val2_1_cast_fu_526_p1 when (sel_tmp7_fu_596_p2(0) = '1') else 
        sel_tmp8_fu_610_p3;
    rev1_fu_348_p2 <= (ult1_fu_342_p2 xor ap_const_lv1_1);
    rev_fu_322_p2 <= (ult_fu_316_p2 xor ap_const_lv1_1);
    sel_tmp10_fu_726_p3 <= 
        p_0115_5_fu_642_p3 when (tmp_48_1_fu_650_p2(0) = '1') else 
        tmp_151_fu_696_p4;
    sel_tmp11_fu_794_p3 <= 
        e_array_V_load_1_1_fu_718_p3 when (tmp_63_1_fu_742_p2(0) = '1') else 
        prehits_2_e_V_read;
    sel_tmp12_fu_802_p2 <= (tmp_63_1_fu_742_p2 xor ap_const_lv1_1);
    sel_tmp13_fu_808_p2 <= (tmp_68_1_fu_778_p2 and sel_tmp12_fu_802_p2);
    sel_tmp14_fu_822_p3 <= 
        p_Val2_1_1_fu_734_p3 when (tmp_63_1_fu_742_p2(0) = '1') else 
        tmp_152_fu_784_p4;
    sel_tmp15_fu_918_p2 <= (tmp_48_2_fu_862_p2 xor ap_const_lv1_1);
    sel_tmp16_fu_924_p2 <= (tmp_62_2_fu_902_p2 and sel_tmp15_fu_918_p2);
    sel_tmp17_fu_938_p3 <= 
        p_0115_5_1_fu_854_p3 when (tmp_48_2_fu_862_p2(0) = '1') else 
        tmp_154_fu_908_p4;
    sel_tmp18_fu_1006_p3 <= 
        e_array_V_load_1_2_fu_930_p3 when (tmp_63_2_fu_954_p2(0) = '1') else 
        prehits_3_e_V_read;
    sel_tmp19_fu_1014_p2 <= (tmp_63_2_fu_954_p2 xor ap_const_lv1_1);
    sel_tmp1_demorgan_fu_370_p2 <= (tmp_fu_328_p3 and rev_fu_322_p2);
    sel_tmp1_fu_712_p2 <= (tmp_62_1_fu_690_p2 and sel_tmp9_fu_706_p2);
    sel_tmp20_fu_1020_p2 <= (tmp_68_2_fu_990_p2 and sel_tmp19_fu_1014_p2);
    sel_tmp21_fu_1034_p3 <= 
        p_Val2_1_2_fu_946_p3 when (tmp_63_2_fu_954_p2(0) = '1') else 
        tmp_155_fu_996_p4;
    sel_tmp22_fu_1130_p2 <= (tmp_48_3_fu_1074_p2 xor ap_const_lv1_1);
    sel_tmp23_fu_1136_p2 <= (tmp_62_3_fu_1114_p2 and sel_tmp22_fu_1130_p2);
    sel_tmp24_fu_1150_p3 <= 
        p_0115_5_2_fu_1066_p3 when (tmp_48_3_fu_1074_p2(0) = '1') else 
        tmp_157_fu_1120_p4;
    sel_tmp25_fu_1218_p3 <= 
        e_array_V_load_1_3_fu_1142_p3 when (tmp_63_3_fu_1166_p2(0) = '1') else 
        prehits_4_e_V_read;
    sel_tmp26_fu_1226_p2 <= (tmp_63_3_fu_1166_p2 xor ap_const_lv1_1);
    sel_tmp27_fu_1232_p2 <= (tmp_68_3_fu_1202_p2 and sel_tmp26_fu_1226_p2);
    sel_tmp28_fu_1246_p3 <= 
        p_Val2_1_3_fu_1158_p3 when (tmp_63_3_fu_1166_p2(0) = '1') else 
        tmp_158_fu_1208_p4;
    sel_tmp29_fu_1342_p2 <= (tmp_48_4_fu_1286_p2 xor ap_const_lv1_1);
    sel_tmp2_fu_388_p2 <= (tmp117_fu_382_p2 and rev1_fu_348_p2);
    sel_tmp30_fu_1348_p2 <= (tmp_62_4_fu_1326_p2 and sel_tmp29_fu_1342_p2);
    sel_tmp31_fu_1362_p3 <= 
        p_0115_5_3_fu_1278_p3 when (tmp_48_4_fu_1286_p2(0) = '1') else 
        tmp_160_fu_1332_p4;
    sel_tmp32_fu_1430_p3 <= 
        e_array_V_load_1_4_fu_1354_p3 when (tmp_63_4_fu_1378_p2(0) = '1') else 
        prehits_5_e_V_read;
    sel_tmp33_fu_1438_p2 <= (tmp_63_4_fu_1378_p2 xor ap_const_lv1_1);
    sel_tmp34_fu_1444_p2 <= (tmp_68_4_fu_1414_p2 and sel_tmp33_fu_1438_p2);
    sel_tmp35_fu_1458_p3 <= 
        p_Val2_1_4_fu_1370_p3 when (tmp_63_4_fu_1378_p2(0) = '1') else 
        tmp_161_fu_1420_p4;
    sel_tmp36_fu_1554_p2 <= (tmp_48_5_fu_1498_p2 xor ap_const_lv1_1);
    sel_tmp37_fu_1560_p2 <= (tmp_62_5_fu_1538_p2 and sel_tmp36_fu_1554_p2);
    sel_tmp38_fu_1574_p3 <= 
        p_0115_5_4_fu_1490_p3 when (tmp_48_5_fu_1498_p2(0) = '1') else 
        tmp_163_fu_1544_p4;
    sel_tmp39_fu_1642_p3 <= 
        e_array_V_load_1_5_fu_1566_p3 when (tmp_63_5_fu_1590_p2(0) = '1') else 
        prehits_6_e_V_read;
    sel_tmp3_fu_496_p2 <= (tmp_62_fu_476_p2 and sel_tmp_fu_490_p2);
    sel_tmp40_fu_1650_p2 <= (tmp_63_5_fu_1590_p2 xor ap_const_lv1_1);
    sel_tmp41_fu_1656_p2 <= (tmp_68_5_fu_1626_p2 and sel_tmp40_fu_1650_p2);
    sel_tmp42_fu_1670_p3 <= 
        p_Val2_1_5_fu_1582_p3 when (tmp_63_5_fu_1590_p2(0) = '1') else 
        tmp_164_fu_1632_p4;
    sel_tmp4_fu_510_p3 <= 
        p_0115_1_cast_cast_fu_408_p1 when (tmp_48_fu_436_p2(0) = '1') else 
        tmp_s_fu_482_p3;
    sel_tmp5_fu_582_p3 <= 
        e_array_V_load_1_s_fu_502_p3 when (tmp_63_fu_530_p2(0) = '1') else 
        prehits_1_e_V_read;
    sel_tmp6_fu_590_p2 <= (tmp_63_fu_530_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_596_p2 <= (tmp_68_fu_566_p2 and sel_tmp6_fu_590_p2);
    sel_tmp8_cast_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_1_fu_412_p3),4));
    sel_tmp8_fu_610_p3 <= 
        p_Val2_1_cast_fu_526_p1 when (tmp_63_fu_530_p2(0) = '1') else 
        tmp_149_fu_572_p4;
    sel_tmp9_fu_706_p2 <= (tmp_48_1_fu_650_p2 xor ap_const_lv1_1);
    sel_tmp_fu_490_p2 <= (tmp_48_fu_436_p2 xor ap_const_lv1_1);
    t_V_1_fu_412_p3 <= 
        prehits_0_t_V_read when (or_cond_fu_336_p2(0) = '1') else 
        ap_const_lv3_0;
    t_V_2_fu_424_p3 <= 
        t_V_fu_362_p3 when (sel_tmp2_fu_388_p2(0) = '1') else 
        sel_tmp8_cast_fu_420_p1;
    t_V_fu_362_p3 <= (ap_const_lv1_1 & curhits_0_t_V_read);
    tmp117_demorgan_fu_376_p2 <= (tmp_148_fu_354_p3 or sel_tmp1_demorgan_fu_370_p2);
    tmp117_fu_382_p2 <= (tmp117_demorgan_fu_376_p2 xor ap_const_lv1_1);
    tmp118_cast_fu_1840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp118_fu_1834_p2),16));
    tmp118_fu_1834_p2 <= std_logic_vector(unsigned(tmp_57_1_cast_fu_1740_p1) + unsigned(tmp119_cast_fu_1830_p1));
    tmp119_cast_fu_1830_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp119_fu_1824_p2),15));
    tmp119_fu_1824_p2 <= std_logic_vector(unsigned(tmp_57_2_cast_fu_1756_p1) + unsigned(tmp_57_cast_fu_1724_p1));
    tmp120_cast_fu_1870_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp120_fu_1864_p2),16));
    tmp120_fu_1864_p2 <= std_logic_vector(unsigned(tmp121_cast_fu_1850_p1) + unsigned(tmp122_cast_fu_1860_p1));
    tmp121_cast_fu_1850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp121_fu_1844_p2),15));
    tmp121_fu_1844_p2 <= std_logic_vector(unsigned(tmp_57_4_cast_fu_1788_p1) + unsigned(tmp_57_3_cast_fu_1772_p1));
    tmp122_cast_fu_1860_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp122_fu_1854_p2),15));
    tmp122_fu_1854_p2 <= std_logic_vector(unsigned(tmp_57_6_cast_fu_1820_p1) + unsigned(tmp_57_5_cast_fu_1804_p1));
    tmp123_cast_fu_1904_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp123_fu_1898_p2),3));
    tmp123_fu_1898_p2 <= std_logic_vector(unsigned(tmp_60_1_cast_fu_1752_p1) + unsigned(tmp124_fu_1892_p2));
    tmp124_fu_1892_p2 <= std_logic_vector(unsigned(tmp_60_2_cast_fu_1768_p1) + unsigned(tmp_60_cast_fu_1736_p1));
    tmp125_fu_1928_p2 <= std_logic_vector(unsigned(tmp126_cast_fu_1914_p1) + unsigned(tmp127_cast_fu_1924_p1));
    tmp126_cast_fu_1914_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp126_fu_1908_p2),3));
    tmp126_fu_1908_p2 <= std_logic_vector(unsigned(tmp_60_4_cast_fu_1800_p1) + unsigned(tmp_60_3_cast_fu_1784_p1));
    tmp127_cast_fu_1924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp127_fu_1918_p2),3));
    tmp127_fu_1918_p2 <= std_logic_vector(unsigned(tmp_60_6_cast_fu_1888_p1) + unsigned(tmp_60_5_cast_fu_1816_p1));
    tmp_11_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hit_dt_V),4));
    tmp_148_fu_354_p3 <= curhits_0_t_V_read(2 downto 2);
    
    tmp_149_fu_572_p4_proc : process(p_Val2_1_cast_fu_526_p1)
    begin
        tmp_149_fu_572_p4 <= p_Val2_1_cast_fu_526_p1;
        tmp_149_fu_572_p4(1) <= ap_const_lv1_1(0);
    end process;

    
    tmp_150_fu_632_p4_proc : process(p_Val2_2_fu_618_p3)
    begin
        tmp_150_fu_632_p4 <= p_Val2_2_fu_618_p3;
        tmp_150_fu_632_p4(0) <= ap_const_lv1_0(0);
    end process;

    
    tmp_151_fu_696_p4_proc : process(p_0115_5_fu_642_p3)
    begin
        tmp_151_fu_696_p4 <= p_0115_5_fu_642_p3;
        tmp_151_fu_696_p4(2) <= ap_const_lv1_1(0);
    end process;

    
    tmp_152_fu_784_p4_proc : process(p_Val2_1_1_fu_734_p3)
    begin
        tmp_152_fu_784_p4 <= p_Val2_1_1_fu_734_p3;
        tmp_152_fu_784_p4(2) <= ap_const_lv1_1(0);
    end process;

    
    tmp_153_fu_844_p4_proc : process(p_Val2_2_1_fu_830_p3)
    begin
        tmp_153_fu_844_p4 <= p_Val2_2_1_fu_830_p3;
        tmp_153_fu_844_p4(0) <= ap_const_lv1_0(0);
    end process;

    
    tmp_154_fu_908_p4_proc : process(p_0115_5_1_fu_854_p3)
    begin
        tmp_154_fu_908_p4 <= p_0115_5_1_fu_854_p3;
        tmp_154_fu_908_p4(3) <= ap_const_lv1_1(0);
    end process;

    
    tmp_155_fu_996_p4_proc : process(p_Val2_1_2_fu_946_p3)
    begin
        tmp_155_fu_996_p4 <= p_Val2_1_2_fu_946_p3;
        tmp_155_fu_996_p4(3) <= ap_const_lv1_1(0);
    end process;

    
    tmp_156_fu_1056_p4_proc : process(p_Val2_2_2_fu_1042_p3)
    begin
        tmp_156_fu_1056_p4 <= p_Val2_2_2_fu_1042_p3;
        tmp_156_fu_1056_p4(0) <= ap_const_lv1_0(0);
    end process;

    
    tmp_157_fu_1120_p4_proc : process(p_0115_5_2_fu_1066_p3)
    begin
        tmp_157_fu_1120_p4 <= p_0115_5_2_fu_1066_p3;
        tmp_157_fu_1120_p4(4) <= ap_const_lv1_1(0);
    end process;

    
    tmp_158_fu_1208_p4_proc : process(p_Val2_1_3_fu_1158_p3)
    begin
        tmp_158_fu_1208_p4 <= p_Val2_1_3_fu_1158_p3;
        tmp_158_fu_1208_p4(4) <= ap_const_lv1_1(0);
    end process;

    
    tmp_159_fu_1268_p4_proc : process(p_Val2_2_3_fu_1254_p3)
    begin
        tmp_159_fu_1268_p4 <= p_Val2_2_3_fu_1254_p3;
        tmp_159_fu_1268_p4(0) <= ap_const_lv1_0(0);
    end process;

    
    tmp_160_fu_1332_p4_proc : process(p_0115_5_3_fu_1278_p3)
    begin
        tmp_160_fu_1332_p4 <= p_0115_5_3_fu_1278_p3;
        tmp_160_fu_1332_p4(5) <= ap_const_lv1_1(0);
    end process;

    
    tmp_161_fu_1420_p4_proc : process(p_Val2_1_4_fu_1370_p3)
    begin
        tmp_161_fu_1420_p4 <= p_Val2_1_4_fu_1370_p3;
        tmp_161_fu_1420_p4(5) <= ap_const_lv1_1(0);
    end process;

    
    tmp_162_fu_1480_p4_proc : process(p_Val2_2_4_fu_1466_p3)
    begin
        tmp_162_fu_1480_p4 <= p_Val2_2_4_fu_1466_p3;
        tmp_162_fu_1480_p4(0) <= ap_const_lv1_0(0);
    end process;

    
    tmp_163_fu_1544_p4_proc : process(p_0115_5_4_fu_1490_p3)
    begin
        tmp_163_fu_1544_p4 <= p_0115_5_4_fu_1490_p3;
        tmp_163_fu_1544_p4(6) <= ap_const_lv1_1(0);
    end process;

    
    tmp_164_fu_1632_p4_proc : process(p_Val2_1_5_fu_1582_p3)
    begin
        tmp_164_fu_1632_p4 <= p_Val2_1_5_fu_1582_p3;
        tmp_164_fu_1632_p4(6) <= ap_const_lv1_1(0);
    end process;

    
    tmp_165_fu_1692_p4_proc : process(p_Val2_2_5_fu_1678_p3)
    begin
        tmp_165_fu_1692_p4 <= p_Val2_2_5_fu_1678_p3;
        tmp_165_fu_1692_p4(0) <= ap_const_lv1_0(0);
    end process;

    tmp_166_fu_1710_p1 <= p_0115_5_5_fu_1702_p3(1 - 1 downto 0);
    tmp_167_fu_1714_p1 <= t_V_2_fu_424_p3(3 - 1 downto 0);
    tmp_48_1_fu_650_p2 <= "1" when (curhits_2_e_V_read = ap_const_lv13_0) else "0";
    tmp_48_2_fu_862_p2 <= "1" when (curhits_3_e_V_read = ap_const_lv13_0) else "0";
    tmp_48_3_fu_1074_p2 <= "1" when (curhits_4_e_V_read = ap_const_lv13_0) else "0";
    tmp_48_4_fu_1286_p2 <= "1" when (curhits_5_e_V_read = ap_const_lv13_0) else "0";
    tmp_48_5_fu_1498_p2 <= "1" when (curhits_6_e_V_read = ap_const_lv13_0) else "0";
    tmp_48_fu_436_p2 <= "1" when (curhits_1_e_V_read = ap_const_lv13_0) else "0";
    tmp_52_1_fu_656_p3 <= (ap_const_lv1_1 & curhits_2_t_V_read);
    tmp_52_2_fu_868_p3 <= (ap_const_lv1_1 & curhits_3_t_V_read);
    tmp_52_3_fu_1080_p3 <= (ap_const_lv1_1 & curhits_4_t_V_read);
    tmp_52_4_fu_1292_p3 <= (ap_const_lv1_1 & curhits_5_t_V_read);
    tmp_52_5_fu_1504_p3 <= (ap_const_lv1_1 & curhits_6_t_V_read);
    tmp_52_fu_442_p3 <= (ap_const_lv1_1 & curhits_1_t_V_read);
    tmp_53_1_fu_664_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_1_fu_656_p3)) else "0";
    tmp_53_2_fu_876_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_2_fu_868_p3)) else "0";
    tmp_53_3_fu_1088_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_3_fu_1080_p3)) else "0";
    tmp_53_4_fu_1300_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_4_fu_1292_p3)) else "0";
    tmp_53_5_fu_1512_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_5_fu_1504_p3)) else "0";
    tmp_53_fu_450_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_52_fu_442_p3)) else "0";
    tmp_54_1_fu_670_p2 <= std_logic_vector(unsigned(tmp_52_1_fu_656_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_54_2_fu_882_p2 <= std_logic_vector(unsigned(tmp_52_2_fu_868_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_54_3_fu_1094_p2 <= std_logic_vector(unsigned(tmp_52_3_fu_1080_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_54_4_fu_1306_p2 <= std_logic_vector(unsigned(tmp_52_4_fu_1292_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_54_5_fu_1518_p2 <= std_logic_vector(unsigned(tmp_52_5_fu_1504_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_54_fu_456_p2 <= std_logic_vector(unsigned(tmp_52_fu_442_p3) - unsigned(t_V_2_fu_424_p3));
    tmp_55_1_fu_676_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_1_fu_656_p3));
    tmp_55_2_fu_888_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_2_fu_868_p3));
    tmp_55_3_fu_1100_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_3_fu_1080_p3));
    tmp_55_4_fu_1312_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_4_fu_1292_p3));
    tmp_55_5_fu_1524_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_5_fu_1504_p3));
    tmp_55_fu_462_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_52_fu_442_p3));
    tmp_57_1_cast_fu_1740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_1_fu_602_p3),15));
    tmp_57_2_cast_fu_1756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_2_fu_814_p3),14));
    tmp_57_3_cast_fu_1772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_3_fu_1026_p3),14));
    tmp_57_4_cast_fu_1788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_4_fu_1238_p3),14));
    tmp_57_5_cast_fu_1804_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_5_fu_1450_p3),14));
    tmp_57_6_cast_fu_1820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_6_fu_1662_p3),14));
    tmp_57_cast_fu_1724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_array_V_load_fu_394_p3),14));
    tmp_58_6_fu_1874_p2 <= std_logic_vector(unsigned(tmp118_cast_fu_1840_p1) + unsigned(tmp120_cast_fu_1870_p1));
    tmp_60_1_cast_fu_1752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_1_fu_1744_p3),2));
    tmp_60_2_cast_fu_1768_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_2_fu_1760_p3),2));
    tmp_60_3_cast_fu_1784_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_3_fu_1776_p3),2));
    tmp_60_4_cast_fu_1800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_4_fu_1792_p3),2));
    tmp_60_5_cast_fu_1816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_5_fu_1808_p3),2));
    tmp_60_6_cast_fu_1888_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_6_fu_1880_p3),2));
    tmp_60_cast_fu_1736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_fu_1728_p3),2));
    tmp_61_6_fu_1934_p2 <= std_logic_vector(unsigned(tmp123_cast_fu_1904_p1) + unsigned(tmp125_fu_1928_p2));
    tmp_62_1_fu_690_p2 <= "1" when (unsigned(diff_V_s_fu_682_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_62_2_fu_902_p2 <= "1" when (unsigned(diff_V_2_fu_894_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_62_3_fu_1114_p2 <= "1" when (unsigned(diff_V_3_fu_1106_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_62_4_fu_1326_p2 <= "1" when (unsigned(diff_V_4_fu_1318_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_62_5_fu_1538_p2 <= "1" when (unsigned(diff_V_5_fu_1530_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_62_fu_476_p2 <= "1" when (unsigned(diff_V_fu_468_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_63_1_fu_742_p2 <= "1" when (prehits_2_e_V_read = ap_const_lv13_0) else "0";
    tmp_63_2_fu_954_p2 <= "1" when (prehits_3_e_V_read = ap_const_lv13_0) else "0";
    tmp_63_3_fu_1166_p2 <= "1" when (prehits_4_e_V_read = ap_const_lv13_0) else "0";
    tmp_63_4_fu_1378_p2 <= "1" when (prehits_5_e_V_read = ap_const_lv13_0) else "0";
    tmp_63_5_fu_1590_p2 <= "1" when (prehits_6_e_V_read = ap_const_lv13_0) else "0";
    tmp_63_fu_530_p2 <= "1" when (prehits_1_e_V_read = ap_const_lv13_0) else "0";
    tmp_64_1_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_2_t_V_read),4));
    tmp_64_2_fu_960_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_3_t_V_read),4));
    tmp_64_3_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_4_t_V_read),4));
    tmp_64_4_fu_1384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_5_t_V_read),4));
    tmp_64_5_fu_1596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_6_t_V_read),4));
    tmp_64_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prehits_1_t_V_read),4));
    tmp_65_1_fu_752_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_1_fu_748_p1)) else "0";
    tmp_65_2_fu_964_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_2_fu_960_p1)) else "0";
    tmp_65_3_fu_1176_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_3_fu_1172_p1)) else "0";
    tmp_65_4_fu_1388_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_4_fu_1384_p1)) else "0";
    tmp_65_5_fu_1600_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_5_fu_1596_p1)) else "0";
    tmp_65_fu_540_p2 <= "1" when (unsigned(t_V_2_fu_424_p3) < unsigned(tmp_64_fu_536_p1)) else "0";
    tmp_66_1_fu_758_p2 <= std_logic_vector(unsigned(tmp_64_1_fu_748_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_66_2_fu_970_p2 <= std_logic_vector(unsigned(tmp_64_2_fu_960_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_66_3_fu_1182_p2 <= std_logic_vector(unsigned(tmp_64_3_fu_1172_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_66_4_fu_1394_p2 <= std_logic_vector(unsigned(tmp_64_4_fu_1384_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_66_5_fu_1606_p2 <= std_logic_vector(unsigned(tmp_64_5_fu_1596_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_66_fu_546_p2 <= std_logic_vector(unsigned(tmp_64_fu_536_p1) - unsigned(t_V_2_fu_424_p3));
    tmp_67_1_fu_764_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_1_fu_748_p1));
    tmp_67_2_fu_976_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_2_fu_960_p1));
    tmp_67_3_fu_1188_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_3_fu_1172_p1));
    tmp_67_4_fu_1400_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_4_fu_1384_p1));
    tmp_67_5_fu_1612_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_5_fu_1596_p1));
    tmp_67_fu_552_p2 <= std_logic_vector(unsigned(t_V_2_fu_424_p3) - unsigned(tmp_64_fu_536_p1));
    tmp_68_1_fu_778_p2 <= "1" when (unsigned(diff_V_1_1_fu_770_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_68_2_fu_990_p2 <= "1" when (unsigned(diff_V_1_2_fu_982_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_68_3_fu_1202_p2 <= "1" when (unsigned(diff_V_1_3_fu_1194_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_68_4_fu_1414_p2 <= "1" when (unsigned(diff_V_1_4_fu_1406_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_68_5_fu_1626_p2 <= "1" when (unsigned(diff_V_1_5_fu_1618_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_68_fu_566_p2 <= "1" when (unsigned(diff_V_1_fu_558_p3) > unsigned(tmp_11_fu_432_p1)) else "0";
    tmp_69_1_fu_838_p2 <= "1" when (unsigned(e_array_V_load_2_fu_814_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_69_2_fu_1050_p2 <= "1" when (unsigned(e_array_V_load_3_fu_1026_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_69_3_fu_1262_p2 <= "1" when (unsigned(e_array_V_load_4_fu_1238_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_69_4_fu_1474_p2 <= "1" when (unsigned(e_array_V_load_5_fu_1450_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_69_5_fu_1686_p2 <= "1" when (unsigned(e_array_V_load_6_fu_1662_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_69_fu_626_p2 <= "1" when (unsigned(e_array_V_load_1_fu_602_p3) < unsigned(e_array_V_load_fu_394_p3)) else "0";
    tmp_fu_328_p3 <= prehits_0_t_V_read(2 downto 2);
    tmp_s_fu_482_p3 <= (ap_const_lv1_1 & p_0115_1_fu_402_p2);
    ult1_fu_342_p2 <= "1" when (unsigned(curhits_0_e_V_read) < unsigned(seed_threshold_V)) else "0";
    ult_fu_316_p2 <= "1" when (unsigned(prehits_0_e_V_read) < unsigned(seed_threshold_V)) else "0";
end behav;
